version: '2.1'
services:
  mysql:
    image: mysql
    container_name: pwcho2018-83722
    ports: 
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mbl
      - MYSQL_PASSWORD=root
    networks:
      bridge_zadanie_1:
        ipv4_address: 10.0.10.3
    healthcheck:
      test: ["CMD", "curl", "-f", "10.0.10.3:3306"]
      interval: 30s
      timeout: 10s
      retries: 5

  java:
    image: michalblaszczykpollub/lab6apache
    container_name: java
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      bridge_zadanie_1:
        ipv4_address: 10.0.10.4

networks:
  bridge_zadanie_1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
          gateway: 10.0.10.1
