version: '2'
services:
  mysql:
    image: mysql
    container_name: pwcho2018-83722
    ports: 
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mbl
      - MYSQL_PASSWORD=root
    networks:
      bridge_zadanie_1:
        ipv4_address: 10.0.10.3
  java:
    image: michalblaszczykpollub/lab6apache
    container_name: java
    depends_on:
      - mysql
    networks:
      bridge_zadanie_1:
        ipv4_address: 10.0.10.4

networks:
  bridge_zadanie_1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
          gateway: 10.0.10.1
